-- V1.64.1__CEC-2196Parametros8375.sql
--
Insert Into Tpzint.Operaciones (Titulo,Identificacion,Nombre,Descripcion,Mnemotecnico,Autorizacion,Formularioprincipal,Proxoperacion,Estado,Tz_Lock,Copias,Suboperacion,Permitebaja,Comportamientoencierre,Requierecontrasena,Permiteconcurrente,Permiteestadodiferido,Icono_Titulo,Estilo) 
values (8350,8375,'Resgate Parcial de Capital','Resgate Parcial de Capital','8375','N',null,null,'P',0,null,0,'S','N','N','N','N',null,0);
--  TTR_CODIGO_TRANSACCION_DEF
insert into Tpzint.Ttr_Codigo_Transaccion_Def (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM)
values (0, 779, 'RESGATE PARCIAL CAPITAL', 'N');
--
insert into Tpzint.Ttr_Codigo_Transaccion_Def (TZ_LOCK, CODIGO_TRANSACCION, DESCRIPCION, UTILIZA_CONTADOR_MOVIM)
values (0, 780, 'RESGATE PARCIAL CAPITAL CREDITO EM CC', 'N');
--
insert into Tpzint.Ttr_Codigo_Transacciones (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK, TARIFA_ID)
values (8375, 1, 779, 0, 0); --D
insert into Tpzint.Ttr_Codigo_Transacciones (CODIGO_OPERACION, CODIGO_INTERNO_MOV, CODIGO_TRANSACCION, TZ_LOCK, TARIFA_ID)
values (8375, 2, 780, 0, 0); --C
--- TTR_TRANSACCIONES_SIST_EXT
BEGIN
	INSERT INTO TPZINT.TTR_TRANSACCIONES_SIST_EXT (TZ_LOCK, CODIGO_OPERACION, CODIGO_TTR, SISTEMA_EXTERNO, DESCRIPCION, CODIGO)
	VALUES (0, 8375, 779, 'CTB', 'RESGATE PARCIAL CAPITAL', (SELECT valor FROM NUMERATORVALUES WHERE NUMERO=10565 AND ANIO=0));
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
	BEGIN
	UPDATE TPZINT.NUMERATORVALUES
	SET VALOR = (SELECT max(codigo)+1 FROM TTR_TRANSACCIONES_SIST_EXT)
	WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 10565;
	INSERT INTO TPZINT.TTR_TRANSACCIONES_SIST_EXT (TZ_LOCK, CODIGO_OPERACION, CODIGO_TTR, SISTEMA_EXTERNO, DESCRIPCION, CODIGO)
	VALUES (0, 8375, 779, 'CTB', 'RESGATE PARCIAL CAPITAL', (SELECT valor FROM NUMERATORVALUES WHERE NUMERO=10565 AND ANIO=0));
	END;
END;
/
UPDATE TPZINT.NUMERATORVALUES
SET VALOR = (SELECT max(codigo)+1 FROM TTR_TRANSACCIONES_SIST_EXT)
WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 10565;
--
BEGIN
	INSERT INTO TPZINT.TTR_TRANSACCIONES_SIST_EXT (TZ_LOCK, CODIGO_OPERACION, CODIGO_TTR, SISTEMA_EXTERNO, DESCRIPCION, CODIGO)
	VALUES (0, 8375, 780, 'CTB', 'RESGATE PARCIAL CAPITAL', (SELECT valor FROM NUMERATORVALUES WHERE NUMERO=10565 AND ANIO=0));
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
	BEGIN
	UPDATE TPZINT.NUMERATORVALUES
	SET VALOR = (SELECT max(codigo)+1 FROM TTR_TRANSACCIONES_SIST_EXT)
	WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 10565;
	INSERT INTO TPZINT.TTR_TRANSACCIONES_SIST_EXT (TZ_LOCK, CODIGO_OPERACION, CODIGO_TTR, SISTEMA_EXTERNO, DESCRIPCION, CODIGO)
	VALUES (0, 8375, 780, 'CTB', 'RESGATE PARCIAL CAPITAL', (SELECT valor FROM NUMERATORVALUES WHERE NUMERO=10565 AND ANIO=0));
	END;
END;
/
UPDATE TPZINT.NUMERATORVALUES
SET VALOR = (SELECT max(codigo)+1 FROM TTR_TRANSACCIONES_SIST_EXT)
WHERE DIA = 0 AND MES = 0 AND ANIO = 0 AND SUCURSAL = 0 AND NUMERO = 10565;
--
insert into Tpzint.Eventos_Transaccion (TZ_LOCK, CODIGO_TRANSACCION, ID_EVENTO, CONDICION, CAMPOS, PRIORIDAD, DESCRIPCION, TIPO_MAPEO, GRABAR_TABLA, ENVIAR_EN_REVERSA)
values (0, 780, 173, null, 'PROOFID=75002;TRANSACTIONDATETIME=641;DOCUMENTID=1051;DOCUMENTTYPE=2970;ORIGINORGANIZATION=3398;ORIGINBRANCH=894;CAPITALACCOUNT=2615;DESTINATIONORGANIZATION=3498;DESTINATIONBRANCH=895;CREDITACCOUNT=50033;CREDITACCOUNTPRODUCT=2237;AMOUNT=4192', 2, 'CAPITAL_TRANSFER', 2, 2, 1);
--
BEGIN
	insert into tpzint.Eventos (TZ_LOCK, ID_EVENTO, CANAL, SUB_CANAL)
	values (0, 173, '5', '4');
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
	NULL;
END;